############################# Shipper ############################################
shipper:

 # The name of the shipper that publishes the network data. It can be used to group
 # all the transactions sent by a single shipper in the web interface.
 # If this options is not defined, the hostname is used.
 name:

 # The tags of the shipper are included in their own field with each
 # transaction published. Tags make it easy to group servers by different
 # logical properties.
 tags: []


 # Uncomment the following if you want to ignore transactions created
 # by the server on which the shipper is installed. This option is useful
 # to remove duplicates if shippers are installed on multiple servers.
 # ignore_outgoing: true


 geoip:
  paths: []


############################# Sniffer ############################################

# Select the network interfaces to sniff the data. You can use the "any"
# keyword to sniff on all connected interfaces.
interfaces:
 device: any



# Configure which protocols to monitor and the ports where they are
# running. You can disable a given protocol by commenting out its
# configuration.
protocols:
  http:
    ports: [80]







    hide_keywords: []


  mysql:
    ports: [3306]






  pgsql:
    ports: [5432]






  redis:
    ports: [6379]



  thrift:
    ports: [9090]

    transport_type: "socket"
    idl_files: []



  mongodb:
    ports: [27017]


    max_docs:
    max_doc_length:

  openflow:
    ports: [6633]

############################# Filters ############################################






############################# Output ############################################

# Configure what outputs to use when sending the data collected by packetbeat.
# You can enable one or multiple outputs by setting enabled option to true.
output:

  # Elasticsearch as output
  # Options:
  # host, port: where Elasticsearch is listening on
  # save_topology: specify if the topology is saved in Elasticsearch
  elasticsearch:
    enabled: true
    host: localhost
    port: 9200
    save_topology: true

  # Redis as output
  # Options:
  # host, port: where Redis is listening on
  # save_topology: specify if the topology is saved in Redis
  redis:
    enabled: false
    host: localhost
    port: 6379
    save_topology: true

  # File as output
  # Options
  # path: where to save the files
  # filename: name of the files
  # rotate_every_kb: maximum size of the files in path
  # number of files: maximum number of files in path
  file:
    enabled: true
    path: "output"
    filename: "packetbeat"
    rotate_every_kb: 1000
    #number_of_files: 7

############################# Processes ############################################



# vim: set ft=jinja:
